/* Generated By:JavaCC: Do not edit this line. GWBasicConstants.java */
package de.hft_stuttgart.cpl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GWBasicConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPAREN = 1;
  /** RegularExpression Id. */
  int CPAREN = 2;
  /** RegularExpression Id. */
  int PLUS = 3;
  /** RegularExpression Id. */
  int MINUS = 4;
  /** RegularExpression Id. */
  int TIMES = 5;
  /** RegularExpression Id. */
  int DIVIDE = 6;
  /** RegularExpression Id. */
  int MODULO = 7;
  /** RegularExpression Id. */
  int NE = 8;
  /** RegularExpression Id. */
  int LE = 9;
  /** RegularExpression Id. */
  int GE = 10;
  /** RegularExpression Id. */
  int LT = 11;
  /** RegularExpression Id. */
  int GT = 12;
  /** RegularExpression Id. */
  int EQUAL = 13;
  /** RegularExpression Id. */
  int FLOAT_NUMBER = 14;
  /** RegularExpression Id. */
  int DEC_NUMBER = 15;
  /** RegularExpression Id. */
  int HEX_NUMBER = 16;
  /** RegularExpression Id. */
  int OCT_NUMBER = 17;
  /** RegularExpression Id. */
  int PRINT = 18;
  /** RegularExpression Id. */
  int LET = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int WEND = 21;
  /** RegularExpression Id. */
  int FOR = 22;
  /** RegularExpression Id. */
  int TO = 23;
  /** RegularExpression Id. */
  int STEP = 24;
  /** RegularExpression Id. */
  int NEXT = 25;
  /** RegularExpression Id. */
  int GOTO = 26;
  /** RegularExpression Id. */
  int GOSUB = 27;
  /** RegularExpression Id. */
  int RETURN = 28;
  /** RegularExpression Id. */
  int DIM = 29;
  /** RegularExpression Id. */
  int STRING = 30;
  /** RegularExpression Id. */
  int NAME = 31;
  /** RegularExpression Id. */
  int EOL = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<>\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "<FLOAT_NUMBER>",
    "<DEC_NUMBER>",
    "<HEX_NUMBER>",
    "<OCT_NUMBER>",
    "\"PRINT\"",
    "\"LET\"",
    "\"WHILE\"",
    "\"WEND\"",
    "\"FOR\"",
    "\"TO\"",
    "\"STEP\"",
    "\"NEXT\"",
    "\"GOTO\"",
    "\"GOSUB\"",
    "\"RETURN\"",
    "\"DIM\"",
    "<STRING>",
    "<NAME>",
    "<EOL>",
    "\" \"",
    "\"\\t\"",
  };

}
